{% set name = "tcllib" %}
{% set version = "2.0" %}
{% set sha256 = "590263de0832ac801255501d003441a85fb180b8ba96265d50c4a9f92fde2534" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://core.tcl-lang.org/tcllib/uv/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: tclsh installer.tcl -no-wait -no-gui -no-html -no-nroff -no-examples

requirements:
  build:
    - tk
  run:
    - tk

test:
  source_files:
    - examples
  commands:   # [not arm64]
    - tclsh examples/logger/logtofile.tcl   # [not arm64]

about:
  home: https://core.tcl-lang.org/tcllib/doc/trunk/embedded/index.md
  license: BSD-3-Clause
  license_family: BSD
  license_file: license.terms
  summary: Tcllib is a collection of utility modules for Tcl.
  doc_url: https://core.tcl-lang.org/tcllib/doc/trunk/embedded/md/toc.md

extra:
  recipe-maintainers:
    - abloemert
