{% set name = "tcllib" %}
{% set version = "1.21" %}
{% set sha256 = "46b2bb5ec8049363ae01645af11bda3bdb5db10629e807d81d1ad46cd1bead50" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://core.tcl-lang.org/tcllib/uv/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: tclsh installer.tcl -no-wait -no-gui -no-html -no-nroff -no-examples

requirements:
  host:
    - tk
  run:
    - tk

test:
  source_files:
    - examples
  commands:
    - tclsh examples/logger/logtofile.tcl

about:
  home: https://core.tcl-lang.org/tcllib/doc/trunk/embedded/index.md
  license: BSD-3-Clause
  license_family: BSD
  license_file: license.terms
  summary: Tcllib is a collection of utility modules for Tcl.
  doc_url: https://core.tcl-lang.org/tcllib/doc/trunk/embedded/md/toc.md

extra:
  recipe-maintainers:
    - abloemert
